name: Makefile CI

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust Setup
      run: make setup

    - name: Build Rust Kernel and Bootloader
      run: make build
    
    - name: Clean Project
      run: make clean
