name: Makefile CI

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run build
      run: make build

    - name: Run clean
      run: make clean
